services:
  - type: web
    name: simulateur-prime
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 4
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: MONGODB_URI
        sync: false          # à saisir dans le dashboard (secret)
      - key: ADMIN_TOKEN
        sync: false
